language: node_js
sudo: false
git:
  submodules: false
  depth: 3
node_js:
  - "4"
  - "8"
before_script:
  - if [ ${TRAVIS_NODE_VERSION%%.*} = "8" ]; then npm install -g nyc coveralls; fi
script:
  - if [ ${TRAVIS_NODE_VERSION%%.*} = "8" ]; then nyc -r lcovonly -r text npm test; else npm test; fi
after_success:
  - if [ ${TRAVIS_NODE_VERSION%%.*} = "8" ]; then coveralls < coverage/lcov.info; fi

